import { Geist, Geist_Mono,Montserrat   } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";

import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

// استدعاء الخطوط في نطاق الوحدة (Module Scope)

const bodyFont =Montserrat({
  subsets:['latin'],
  weight: ["400","900"],
})
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const lalezar = Lalezar({
//   subsets: ["arabic"],
//   weight: ["400"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bodyFont.className} `}>
      <Navbar/>
        {children}
      </body>
    </html>
  );
}
